[tool.poetry]
name = "tap-oracle"
version = "0.3.4"
description = ""
authors = ["Stitch"]
homepage = "https://singer.io"
classifiers = ["Programming Language :: Python :: 3 :: Only"]

[tool.poetry.dependencies]
python = "~3.7"
singer-python = "~5.3.1"
cx_Oracle = "~6.1"
strict-rfc3339 = "~0.7"

[tool.poetry.dev-dependencies]

[tool.poetry.plugins."console_scripts"]
tap-oracle = "tap_oracle:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
